# Generated by Django 5.2 on 2025-04-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chanel_name', models.CharField(max_length=100)),
                ('chanel_username', models.CharField(max_length=100)),
                ('chanel_id', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
